spring.application.name=order-service

server.port=8082

spring.datasource.url=jdbc:h2:mem:orderdb


# Configuration de Resilience4j

# ==================================

# On définit un Circuit Breaker nommé 'productServiceBreaker'

resilience4j.circuitbreaker.instances.productServiceBreaker.register-health-indicator=true

# Taille du buffer circulaire en état FERMÉ.

# Le disjoncteur agrège les résultats des 5 derniers appels.

resilience4j.circuitbreaker.instances.productServiceBreaker.sliding-window-size=5

# Type de fenêtre : basé sur le nombre d'appels (COUNT_BASED)

resilience4j.circuitbreaker.instances.productServiceBreaker.sliding-window-type=COUNT_BASED

# Seuil d'échec en pourcentage. Si 60% des 5 derniers appels échouent,

# le disjoncteur s'ouvre.

resilience4j.circuitbreaker.instances.productServiceBreaker.failure-rate-threshold=60

# Temps d'attente en état OUVERT avant de passer en SEMI-OUVERT.

resilience4j.circuitbreaker.instances.productServiceBreaker.wait-duration-in-open-state=10s

# Nombre d'appels autorisés en état SEMI-OUVERT.

resilience4j.circuitbreaker.instances.productServiceBreaker.permitted-number-of-calls-in-half-open-state=2





